### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by ali2021** [EIS-Bonn/Luzzu#17] opened 2016-10-30 14:07 UTC
![ubuntu 64-bit-2016-10-30-00-53-22](https://cloud.githubusercontent.com/assets/2012818/19837079/7a21fe44-9ec7-11e6-91fd-f5ca0feef24d.png)

**Comment by pepe3059** [comment] 2017-01-30 23:58
I got the same problem. Did you solve it?

**Comment by ali2021** [comment] 2017-02-05 20:03
no sir.

**Comment by jerdeb** [comment] 2017-02-06 00:16
Hi all,

Apologies for my delayed reply. You might need to clone and build this before: https://github.com/diachron/quality . This repo contains various quality metrics and there is also some stuff (metric utilities) which has to be moved to this project - however it is still in the pipeline. In the meantime, you could download this script: https://dl.dropboxusercontent.com/u/5895290/luzzu-setup-docker/luzzu.sh and install everything. It _should_ work, however if not please let me know and I can help you further.

Cheers,
Jer

**Comment by pepe3059** [comment] 2017-02-22 23:12
Hi Jer,


Thank you very much for your recommendations. I tried to install Luzzu through the bash script. However, I obtained some errors regarding versions and static paths.

1.- I got a problem of @override method implementation, thus I changed luzzu version in quality/pom.xml from 1.0.2 to 2.0.0 and it compiled
<luzzu.version>2.0.0</luzzu.version>

2.- https://dl.dropboxusercontent.com/u/5895290/luzzu/log4j.xml does not exist or is no longer available, thus I omitted this step in the script (replacement)

"Dmaven.test.skip=true" is really needed for installing :o

3.- I changed QUALITY_METADATA_BASE_DIR inside /Luzzu/luzzu-operations/src/main/resources/properties/directories.properties and recompile because it referred to a local directory of the developer

4.- For some reason, metrics are not taken from luzzu-communications/externals, so I copied "externals" to the Luzzu root



Unfortunately, I got errors after running the quality/examples


*bash efo236.sh 
{ "Dataset": "", "Agent": "http://localhost:8080/Luzzu/", "Outcome": "ERROR", "ErrorMessage": "null", "ErrorCode": "1487802774204" }


*and running efo234.sh apparently works but at the end nothing is written and errors are deployed (I include only a fragment of the output to avoid redundant instructions)
[output.txt](https://github.com/EIS-Bonn/Luzzu/files/795076/output.txt)

Moreover, some files are no processed (jena requiements?)
TRACE LocatorClassLoader - Failed to open: location-mapping.ttl



Probably I forgot to include something or a path is misplaced. Hope you can help me, thank you for your time.

Best,
José

**Comment by seralf** [comment] 2017-05-19 11:50
Hi the dropbox link seems not to work (or at least it does not work anymore).
Moreover I can confirm there are issues with diachron/quality compilation in maven: I tried to recompile it directly with maven on my machine, and had some errors, as in the [issue #63](https://github.com/diachron/quality/issues/63)

**Comment by jerdeb** [comment] 2017-05-19 12:06
@seralf Try this: https://www.dropbox.com/s/0h46ttars36y5hr/luzzu.sh . I will look into the other issue later on.

**Comment by seralf** [comment] 2017-05-19 13:27
thanks!


2017-05-19 14:06 GMT+02:00 Jeremy Debattista <notifications@github.com>:

**Comment by jerdeb** [comment] 2017-05-19 14:41
@seralf, I have updated the luzzu.sh script.. dropbox changed all paths

**Comment by seralf** [comment] 2017-05-19 15:19
thanks very much, I'll give a try as soon as possible, and let you know

**Comment by seralf** [comment] 2017-05-19 15:36
uhm I still have the same errors :-(
I'm currently on a win 10 machine with java 8 (I'm forced to use this environment), so I had to install gnu wget  etc. I suppose some issues could be from that.

What about providing a Vagrant pre-configured box, instead?
something a user might want to install and simply change the general configurations, which could be externalized on a shared folder on the host. This could let you control the default installation by configuring a boot script with a controlled sequence of operations (wget, maven install in the right sequence, etc ) and it's more reproducible.

**Comment by jerdeb** [comment] 2017-05-19 15:45
I understand. Unfortunately, this project has no funding at the moment (it was part of my PhD thesis) so all bugs have to be fixed in my free time. I will add the Vagrant configuration as one of the todos in the future. 

In the meantime you can follow the following steps:

1) Clone the quality metrics
`git clone https://github.com/diachron/quality.git`

2) Replace the main pom.xml file found in the cloned folder with [this pom.xml file](https://www.dropbox.com/s/dr4kgaqswghx8qn/pom.xml) t

3) Install the quality metrics using maven (this is a bug which i need to fix as for some reason we are using some dependencies from that project)
`mvn clean install -Dmaven.test.skip=true -Dfile.encoding=UTF-8`

4) Clone luzzu
`git clone https://github.com/EIS-Bonn/Luzzu.git`

5) Install luzzu 
`mvn clean install -Dmaven.test.skip=true;`

This should work. I will try to fix the compilation problems this weekend, including moving the dependency from the quality project to luzzu.

Let me know

**Comment by seralf** [comment] 2017-05-19 21:15
thanks very much, I'll do some testing as i'll find time next week, and let
you know if it works!

2017-05-19 17:45 GMT+02:00 Jeremy Debattista <notifications@github.com>:

**Comment by jerdeb** [comment] 2017-06-09 19:18
Hi @seralf, @pepe3059, @ali2021 

Apologies for the delay.

This issue should be fixed now. The problem was incorrect versions in the POM. I fixed and updated both projects.

Please download the following script file which installs luzzu and the metrics: http://eis-bonn.github.io/Luzzu/setup/luzzu.sh 
This was tried on an Ubuntu terminal.

Make sure to change the paths before running the script. The script might take some time the first time round, however, I am going through the dependencies to remove the unneccessary ones. Let me know how it goes for you.

Best,
Jeremy

**Closed by jerdeb** 2017-06-09 19:18 UTC
Labels: high priority development

**Comment by pepe3059** [comment] 2017-06-09 20:32
Thank you @jerdeb for your great work, I'll use Luzzu on my PhD thesis to evaluate RDF data represented from scratch

Cheers,
José

**Comment by seralf** [comment] 2017-06-09 20:36
thanks! I didn't find time to run again some test again yet, but I'll let
you know if it works, thank you again

2017-06-09 22:32 GMT+02:00 pepe3059 <notifications@github.com>:

**Comment by jerdeb** [comment] 2017-06-09 22:03
@pepe3059 its good to hear that! Luzzu was part of my PhD thesis :) good luck!
